# id_column: "transaction_id"
# ali_id_column: "transaction_id"

database1: mysql # postgres, oracle, aws, ali, mysql, clickhouse
database2: clickhouse # postgres, oracle, aws, ali, mysql, clickhouse

databases: ["mysql", "clickhouse"]
data_type: integer # integer, string, date
is_using_manual_queries: yes # yes, or no 
batch_size: 10000
threshold: 1 # threshold for fuzzy logic, used only for string validation



# if using filter period please fill this item, and if not comment this item
# start_date: "2014-01-01"
# end_date: "2024-12-30"

composite_id_columns: ["id"] # composite id, if in table have unique id fill this with unique id

check_column: "asset_model_id" # Kolom yang akan diverifikasi



aws_table_name:
ali_table_name:
postgres_table_name: "asset_rtmd_histories"
oracle_table_name: "orders"
clickhouse_table_name: "raw_asset_rtmd_histories"  # ClickHouse table name
mysql_table_name: "asset_rtmd_histories"       # MySQL table name

postgres_database_date_column: "month_id"  # date column for first database
oracle_database_date_column: "month_id" # date column for second database
clickhouse_database_date_column: "month_id" # date column for ClickHouse database
mysql_database_date_column: "month_id" # date column for MySQL database
aws_database_date_column:
ali_database_date_column:






queries:
  first_query: |
    SELECT 
    id,
    device_status
    FROM asset_rtmd_histories 


  second_query: |
    SELECT 
    id,
    device_status
    FROM raw_asset_rtmd_histories final

  
